# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: true
os:
  - linux

after_success:
  - Rscript -e 'covr::coveralls()'

before_install:
  sudo apt-get update &
  sudo apt-get install libgit2-dev

before_deploy:
  sudo apt-get update &
  sudo apt-get install libharfbuzz-dev libfribidi-dev &
  Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
